openapi: 3.0.0
info:
  title: Service Reservas App
  description: Service Reservas App
  termsOfService: https://sample.com/terms/
  contact:
    name: API Support
    url: https://www.sample.com/support
    email: support@sample.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: "1.0"
servers:
  - url: http://localhost:5000/service--reservas-app
  - url: https://apps-dev.grupo.com.br/sample
  - url: http://localhost:9090/service--reservas-app
components:
  schemas:
    GeneralError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    ResponseClienteError:
      type: object
      properties:
        status:
          type: string
          description: Error Status
        errorCode:
          type: string
          description: ErrorCode
        message:
          type: string
          description: Error Message
    ErrorReserva:
      type: object
      properties:
        code:
          type: string
          description: Error Code
        message:
          type: string
          description: Error Description
    SampleResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
    RequestReserva:
      type: object
      properties:
        nomeCliente:
          type: string
        dataEntrada:
          type: string
        dataSaida:
          type: string
        numeroHospedes:
          type: string
    ResponseReserva:
      type: object
      properties:
        nomeCliente:
          type: string
        dataEntrada:
          type: string
        dataSaida:
          type: string
        numeroHospedes:
          type: string
    RequestCliente:
      type: object
      properties:
        nomeCompleto:
          type: string
        telefone:
          type: string
        email:
          type: string
        cpf:
          type: string
        dataNascimento:
          type: string
        sexo:
          type: string
        endereco:
          $ref: '#/components/schemas/RequestEndereco'
    ResponseCliente:
      type: object
      properties:
        nomeCompleto:
          type: string
        telefone:
          type: string
        email:
          type: string
        cpf:
          type: string
        dataNascimento:
          type: string
        sexo:
          type: string
        endereco:
          $ref: '#/components/schemas/ResponseEndereco'
    RequestEndereco:
      type: object
      properties:
        logradouro:
          type: string
        bairro:
          type: string
        localidade:
          type: string
        uf:
          max: 2
          min: 2
          type: string
        cep:
          max: 9
          min: 8
          type: string
        numero:
          type: string
        complemento:
          type: string
    ResponseEndereco:
      type: object
      properties:
        rua:
          type: string
        cidade:
          type: string
        estado:
          type: string
        cep:
          type: string
        complemento:
          type: string
  responses:
    GeneralError:
      description: General Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GeneralError'
paths:

  /cliente:
    post:
      tags:
        - client
      summary: Create new client
      description: Create new client
      operationId: createClient
      requestBody:
        description: Create a new client
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestCliente'
          application/xml:
            schema:
              $ref: '#/components/schemas/RequestCliente'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RequestCliente'
        required: true
      responses:
        '200':
          description: Client created with sucess
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCliente'
            application/xml:
              schema:
                $ref: '#/components/schemas/ResponseCliente'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseClienteError'
        '422':
          description: Validation exception
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseClienteError'
        '500':
          description: Internal Server Err
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseClienteError'
    /getCliente/{cpf}:
      get:
        tags:
          - cpfCliente
        summary: Find cliente by cpf
        description: Returns a client
        operationId: getClienteCpf
        parameters:
          - name: cpf
            in: path
            description: cpf of client to return
            required: true
            schema:
              type: integer
              format: int64
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ResponseCliente'
              application/xml:
                schema:
                  $ref: '#/components/schemas/ResponseCliente'
          '404':
            description: Client not found
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ResponseClienteError'
          '400':
            description: Invalid input
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ResponseClienteError'
          '422':
            description: Validation exception
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ResponseClienteError'
          '500':
            description: Internal Server Error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ResponseClienteError'


  /reservas:
    post:
      tags:
        - reserve
      summary: Create a new reserva
      description: Create a new reserva
      operationId: createReserva
      requestBody:
        description: Create a new reserva
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestReserva'
          application/xml:
            schema:
              $ref: '#/components/schemas/RequestReserva'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RequestReserve'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseReserva'
            application/xml:
              schema:
                $ref: '#/components/schemas/ResponseReserva'
        '400':
          description: Invalid input
        '422':
          description: Validation exception


